// Module2_FrontendDev_Elakiyan/handson_06/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

export default function Header({ siteName }) {
  const enrolledCount = useSelector((state) => state.enrollment.enrolledCourses.length);

  return (
    <header className="header">
      <div className="site-name">{siteName}</div>
      <nav aria-label="Main navigation">
        <ul>
          <li><Link to="/">Home</Link></li>
          <li><Link to="/courses">Courses</Link></li>
          <li><Link to="/profile">Profile ({enrolledCount})</Link></li>
        </ul>
      </nav>
    </header>
  );
}

// Module2_FrontendDev_Elakiyan/handson_08/src/components/Header.vue
<script setup>
import { useEnrollmentStore } from "../stores/enrollment.js";

const store = useEnrollmentStore();
</script>

<template>
  <header class="header">
    <div class="site-name">Student Portal</div>
    <nav aria-label="Main navigation">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile ({{ store.enrolledCourses.length }})</RouterLink>
    </nav>
  </header>
</template>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 24px;
  background-color: #1e293b;
  color: #fff;
}
nav a {
  color: #fff;
  text-decoration: none;
  margin-left: 20px;
}
</style>
