// Module2_FrontendDev_Elakiyan/handson_07/src/app/course-card/course-card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-course-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './course-card.component.html',
})
export class CourseCardComponent {
  @Input() name!: string;
  @Input() code!: string;
  @Input() credits!: number;
  @Input() grade!: string;
}

<article class="course-card">
  <h3>{{ name }}</h3>
  <p>{{ code }}</p>
  <span>{{ credits }} credits</span>
  <p class="grade">Grade: {{ grade }}</p>
</article>

// Module2_FrontendDev_Elakiyan/handson_05/src/components/CourseCard.jsx
export default function CourseCard({ id, name, code, credits, grade, onEnroll }) {
  return (
    <article className="course-card">
      <h3>{name}</h3>
      <p>{code}</p>
      <span>{credits} credits</span>
      <p className="grade">Grade: {grade}</p>
      <button onClick={() => onEnroll(id)}>Enroll</button>
    </article>
  );
}
